replicaCount: 1

image:
  imagePullSecretName: ecr-creds
  repository: 782197776658.dkr.ecr.us-east-1.amazonaws.com/madmeme/backend
  pullPolicy: IfNotPresent
  tag:

imgFlipUsername:
imgFlipPassword:
apiNinjasKey:

httpRoute:
  enabled: true
  annotations: {}
  parent:
    name: primary
    namespace: gateway
  hostname: madmeme.levilutz.com

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /ping
    port: http
readinessProbe:
  httpGet:
    path: /ping
    port: http

mongo:
  pvc:
    size: 1Gi
    storageClass: do-block-storage-retain
  resources:
    limits:
      cpu: 100m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 384Mi
