apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ printf "%s-regcred" ( include "madmeme.fullname" . ) }}
  labels:
    {{- include "madmeme.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.creds.host .Values.image.creds.username .Values.image.creds.password (printf "%s:%s" .Values.image.creds.username .Values.image.creds.password | b64enc) | b64enc }}
