apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
  name: {{ include "mongo.fullname" . }}
type: Opaque
data:
  imgFlipUsername: {{ .Values.imgFlipUsername | b64enc }}
  imgFlipPassword: {{ .Values.imgFlipPassword | b64enc }}
  apiNinjasKey: {{ .Values.apiNinjasKey | b64enc }}
