apiVersion: v1
kind: Service
metadata:
  name: {{ include "madmeme.fullname" . }}
  labels:
    {{- include "madmeme.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "madmeme.selectorLabels" . | nindent 4 }}
