apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
  name: {{ include "mongo.fullname" . }}
type: Opaque
data:
  {{- if ((lookup "v1" "Secret" (.Release.Namespace) (include "mongo.fullname" .)) | len) }}
  password: {{ (lookup "v1" "Secret" (.Release.Namespace) (include "mongo.fullname" .)).data.password }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  user: {{ "root" | b64enc }}
