replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "7.0.9"

resources:
  limits:
    cpu: 25m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 128Mi

pvc:
  size: 1Gi
  storageClass:
