replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "7.0.9"

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

pvc:
  size: 1Gi
  storageClass:
