name: Build

on:
  push:
    tags:
      - "**"

jobs:
  buildpush:
    name: Build and Push

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PRIVATE_DOCKER_HOST }}
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Build and Push Service
        uses: docker/build-push-action@v5
        with:
          context: backend
          target: prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.PRIVATE_DOCKER_HOST }}/${{ secrets.MADMEME_IMAGE }}:${{ github.ref_name }}
