name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Which tag to deploy

jobs:
  verify-images:
    name: Verify Images Exist

    runs-on: ubuntu-latest

    steps:
      - name: Verify Image Exists
        run: |
          curl \
            --fail \
            -u "${{ secrets.PRIVATE_DOCKER_USERNAME }}:${{ secrets.PRIVATE_DOCKER_PASSWORD }}" \
            -H "Accept: application/vnd.oci.image.manifest.v1+json" \
            -H "Accept: application/vnd.oci.image.index.v1+json" \
            "https://${{ secrets.PRIVATE_DOCKER_HOST }}/v2/${{ secrets.MADMEME_IMAGE }}/manifests/${{ github.event.inputs.tag }}"

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    needs:
      - verify-images

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load kube config
        run: |
          mkdir "${HOME}"/.kube
          echo "${{ secrets.KUBE_CONFIG_64 }}" | base64 -d > "${HOME}/.kube/config"
          chmod 600 "${HOME}/.kube/config"
